feat: 0.3.9 Add KLS_GULP_FILE(), kls_new_dbg() (#44)
* feat: KOLISEO_HAS_GULP

* feat: add KLS_GULP_FILE()

* feat: bump amboso to 1.7.2

* fix: add astyle to anviltest workflow

* feat: add kls_new_dbg()

diff --git a/tests/ok/check_format b/tests/ok/check_format
--- a/tests/ok/check_format
+++ b/tests/ok/check_format
@@ -1,10 +1,13 @@
 #!/bin/bash
 
+
 # Define the source directory
-SRC_DIR="src"
+SRC_DIR="./src"
 
 # Specify the path to the configuration file
-CONFIG_FILE=".astylerc"
+CONFIG_FILE="./.astylerc"
+
+[[ -f $CONFIG_FILE ]] || { printf "[ERROR] $CONFIG_FILE was not found.\n"; exit 1; } ;
 
 # List of source files
 kls_SOURCES=("$SRC_DIR"/*.c "$SRC_DIR"/*.h)
@@ -17,7 +20,7 @@ for src in "${kls_SOURCES[@]}"; do
     astyle --options="$CONFIG_FILE" "$src.tmp" >/dev/null
 
     # Check if the temporary file differs from the original file
-    if ! diff -q "$src" "$src.tmp" &> /dev/null; then
+    if ! diff -q "$src" "$src.tmp" &>/dev/null ; then
         printf "\033[1;31m$src\e[0m needs formatting"
     fi
 
